### ISSUE TITLE
Didn't work for me: TypeError (not indexable)

### ISSUE THREAD

**Issue by madtyn** [davidcorne/Design-Patterns-In-Python#2]
I tried to run your example, but it gave an error:

TypeError: 'dict_keys' object does not support indexing

It can be fixed by replacing the first line in questions_and_answers() method:

key = random.choice(self.q_and_a.keys())

for this one

key = random.choice(list(self.q_and_a.keys()))

**Comment by davidcorne** [comment]
Hi, thanks for the feedback. What version of python are you using? Because testing on my installed version (2.7.9) it works fine. In 3.3+ I know it returns a dict view object which won't be compatible with random.choice() but there are a few other tweaks needed for 3.3+ anyway (Tkinkter rename for example)

**Comment by madtyn** [comment]
Python 3.5.

I think the 'tkinter' renaming and the list() replacing was all I did for
getting it to work, so it's easily converted to Python 3.x
